# Tracking Dot


*Requires Python3*
If you have both Python 2.7 and Python 3 installed, you might want to call the library files explicitely in the deda directory via `bin/deda_parse_print.py <scanned-image>`. This helped me fix an issue.

### Resources
- https://www.helpnetsecurity.com/2018/06/27/app-masks-printers-tracking-dots/
- https://dl.acm.org/citation.cfm?doid=3206004.3206019
- https://github.com/dfd-tud/deda
